language: node_js

node_js:
  - 12

cache:
  npm: true

services:
  - docker

branches:
  only:
    - master

install:
  - npm install

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      name: "Running tests!"
      script:
        - npm run test
    - stage: build
      name: "Docker build and push"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t node-latest .
        - docker images
        - docker tag node-latest $DOCKER_USERNAME/node-latest
        - docker push $DOCKER_USERNAME/node-latest