language: node_js

node_js:
  - 12

cache:
  npm: true

services:
  - docker

branches:
  only:
    - master

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
install:
  - npm install

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      name: "Running tests!"
      script:
        - npm run test
    - stage: build
      name: "Docker build and push"
      env: GIT_VERSION=${git describe --always}
      script:
        - echo $GIT_VERSION
        - docker build -t node-server:$GIT_VERSION .
        - docker images
        - docker tag node-server:${GIT_VERSION} $DOCKER_USERNAME/node-server:${GIT_VERSION}
        - docker push $DOCKER_USERNAME/node-server:${GIT_VERSION}