version: "3.5"
services:
  node-be:
    build: .
    command: node server.js
    ports:
      - target: 8000
        published: 80
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-vol
        target: /code
  redis:
    image: "redis:latest"
    networks:
      app-net:

networks:
  app-net:

volumes:
  app-vol: